imp: 优化了群组管理，提升速度，并支持更多平台
sealdice/sealdice-ui pull request #122
Opened 2023-12-28 09:41 UTC by fy0

不过行为还没改，退群要改成什么呢？

https://github.com/sealdice/sealdice-core/issues/398

2023-12-28 09:43 UTC, fy0 commented
![image](https://github.com/sealdice/sealdice-ui/assets/1579850/7380ce39-a189-471c-9ecb-3d1abcfa9e5a)

2023-12-28 09:47 UTC, Xiangze-Li commented
Dc-like 平台可以把退群按钮置灰？

可能需要加上分页，印象里一次请求过多数据似乎有崩溃风险。
这里的分页在后端可以通过遍历实现，性能瓶颈应不在后端。

2023-12-28 10:12 UTC, fy0 commented
> Dc-like 平台可以把退群按钮置灰？
> 
> 可能需要加上分页，印象里一次请求过多数据似乎有崩溃风险。 这里的分页在后端可以通过遍历实现，性能瓶颈应不在后端。

不在后端，虚拟列表即可。有崩溃风险吗？

2023-12-28 10:15 UTC, Xiangze-Li commented
> 不在后端，虚拟列表即可。有崩溃风险吗？

可以问问一云，我记得他说在群组过多时会出问题。

2023-12-28 14:18 UTC, JustAnotherID requested changes

2023-12-28 14:18 UTC, JustAnotherID commented on src/components/misc/PageMiscGroup.vue
> +              <el-button type="danger" size="small" :icon="Close" plain @click="quitGroup(i, index, j.toString())">退群
直接改成叫「退出」吧，有频道还叫退群不太合适。

2023-12-28 14:18 UTC, JustAnotherID commented on src/components/misc/PageMiscGroup.vue
> +                {{ j.toString().slice(-4) }}</el-button>
感觉这个后缀可以拿掉？

2023-12-29 00:06 UTC, Xiangze-Li commented on src/components/misc/PageMiscGroup.vue
> +                {{ j.toString().slice(-4) }}</el-button>
这个还是要留着。如果有多个账号同时在一个群里，每个按钮只对应一个账号的退群。后缀是用来区分账号的。

不过可以考虑是，如果一个群只有一个账号在，就省略后缀（开发难度又增加力）

2023-12-29 08:24 UTC, fy0 commented on src/components/misc/PageMiscGroup.vue
> +              <el-button type="danger" size="small" :icon="Close" plain @click="quitGroup(i, index, j.toString())">退群
修改哩

2023-12-29 08:29 UTC, JustAnotherID approved these changes
TL;DR

2023-12-29 08:29 UTC, merged