feat(js): 实现插件配置项有序展示，并优先展示 description
sealdice/sealdice-ui pull request #195
Opened 2024-05-22 11:59 UTC by MintCider

关联后端PR：https://github.com/sealdice/sealdice-core/pull/802

## Disclaimer

没写过 Vue，模仿上下文写的（x 请仔细检查

2024-05-22 12:04 UTC, MintCider commented on src/components/mod/PageJs.vue
>                        <template v-if="(c as unknown as JsPluginConfigItem).value !== (c as unknown as JsPluginConfigItem).defaultValue">
实际展示时使用一个条件式展示 `description`，但像这种 `template` 下，应该使用 `key` 还是 `description` 呢？应该修改么？

2024-05-22 15:14 UTC, MintCider commented on src/type.d.ts
> +  configs: JsPluginConfigItem[];
只改了这一行 然后和新 API 模型的配合看起来似乎也许大概非常良好

2024-05-22 17:05 UTC, JustAnotherID requested changes

2024-05-22 17:05 UTC, JustAnotherID commented on src/components/mod/PageJs.vue
> +                          <el-text size="large">{{ (c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key }}</e
不太对，`key` 和 `description` 不是非此即彼的值。`key` 相当于变量名，`description` 是注释，这两个不能像这样来合并。
类似于染色器中的选项「骰子指令过滤：开启后，不显示pc指令，正常显示指令结果」，「骰子指令过滤」是 key，「开启后，不显示pc指令，正常显示指令结果」是 `description`。

2024-05-22 17:05 UTC, JustAnotherID commented on src/components/mod/PageJs.vue
> +                      <el-form-item label="字符串配置项:">{{(c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key}}<
同上，这两个值可能是同时存在的，不应该合并。

2024-05-22 17:05 UTC, JustAnotherID commented on src/components/mod/PageJs.vue
> +                      <el-form-item label="字符串配置项:">{{(c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key}}<
以及大量的类似 `c as unknown as JsPluginConfigItem` 的类型转换代码似乎都是不必要的。

2024-05-22 17:06 UTC, JustAnotherID commented on src/components/mod/PageJs.vue
> +                      <el-form-item label="字符串配置项:">{{(c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key}}<
很多地方都类似，就不一一赘述了。

2024-05-23 05:48 UTC, MintCider commented on src/components/mod/PageJs.vue
> +                          <el-text size="large">{{ (c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key }}</e
这个主要是考虑到插件作者写配置项的过程中，快速调取配置项与可读性的矛盾。毕竟通常来说这种配置项的 key 都是英文缩写吧？

如果像「骰子指令过滤：开启后，不显示pc指令，正常显示指令结果」一样，将「骰子指令过滤」作为 key，那 `getBoolConfig(ext, "骰子指令过滤")` 似乎太过麻烦了。

而下面这种写法我觉得比较符合直觉：

```js
setBoolConfig(ext, "dice_filter", "开启后，不显示pc指令，正常显示指令结果");
getBoolConfig(ext, "dice_filter")

setIntConfig(ext, "repeat_num", "请填入触发骰子复读需要的已复读消息条数");
getIntConfig(ext, "repeat_num")

setStringConfig(ext, "sys_prompt", "请填入系统提示词（可以修改 AI 人设）");
getStringConfig(ext, "sys_prompt")
```

但是这样的话 key 的可读性对用户来说又变得很差，所以我才想要不要干脆不展示。

或许应该问问 UI/UX 同学的意见？

2024-05-23 05:48 UTC, MintCider commented on src/components/mod/PageJs.vue
> +                      <el-form-item label="字符串配置项:">{{(c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key}}<
> 以及大量的类似 `c as unknown as JsPluginConfigItem` 的类型转换代码似乎都是不必要的。

这个是原来就有的（x 我不懂 Vue

2024-05-23 06:41 UTC, Szzrain commented on src/components/mod/PageJs.vue
> +                      <el-form-item label="字符串配置项:">{{(c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key}}<
c as unknown as JsPluginConfigItem 是我当时为了消除 linter 莫名其妙的报错写的，按理说是不需要

2024-05-23 07:12 UTC, Xiangze-Li commented on src/components/mod/PageJs.vue
> +                          <el-text size="large">{{ (c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key }}</e
> 但是这样的话 key 的可读性对用户来说又变得很差，所以我才想要不要干脆不展示。

你例子中的情况恰好是必须将 key 和 description 都显示出来。因为 description 描述了功能和内容要求，但刚好没有包括这个配置项的「名称」。描述一个项目时，名称是完全必要的。

2024-05-23 07:19 UTC, MintCider commented on src/components/mod/PageJs.vue
> +                          <el-text size="large">{{ (c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key }}</e
> > 但是这样的话 key 的可读性对用户来说又变得很差，所以我才想要不要干脆不展示。
> 
> 你例子中的情况恰好是必须将 key 和 description 都显示出来。因为 description 描述了功能和内容要求，但刚好没有包括这个配置项的「名称」。描述一个项目时，名称是完全必要的。即使名称并不是很好读，但是只要能够明确区分、能够复制，就足够了。

OK 说服我了

2024-05-23 07:24 UTC, MintCider commented on src/components/mod/PageJs.vue
> +                      <el-form-item label="字符串配置项:">{{(c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key}}<
这个类型转换我就先不动了（x

2024-05-23 07:25 UTC, MintCider commented on src/components/mod/PageJs.vue
> +                          <el-text size="large">{{ (c as unknown as JsPluginConfigItem).description ? (c as unknown as JsPluginConfigItem).description : (c as unknown as JsPluginConfigItem).key }}</e
已撤销

2024-05-23 07:30 UTC, JustAnotherID approved these changes

2024-05-23 07:32 UTC, JustAnotherID commented
等待与 core 一起合并

2024-05-23 07:40 UTC, merged